// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringStationAPI.Database;

#nullable disable

namespace MonitoringStationAPI.Migrations
{
    [DbContext(typeof(IoTDataCollectorDBContext))]
    [Migration("20240512180509_AddedSensors")]
    partial class AddedSensors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MonitoringStationAPI.Models.Sensors", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("MonitoringStationAPI.Models.SensorsData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataCollectionInterval")
                        .HasColumnType("TEXT");

                    b.Property<float>("DataRangeMax")
                        .HasColumnType("REAL");

                    b.Property<float>("DataRangeMin")
                        .HasColumnType("REAL");

                    b.Property<float?>("NormalThresholdMax")
                        .HasColumnType("REAL");

                    b.Property<float?>("NormalThresholdMin")
                        .HasColumnType("REAL");

                    b.Property<string>("Parameter")
                        .HasColumnType("TEXT");

                    b.Property<double>("ParameterValue")
                        .HasColumnType("REAL");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Warning")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("SensorsData");
                });
#pragma warning restore 612, 618
        }
    }
}
