version: '3.8'

services:
  backend:
    image: atifhussain28/backend:latest
    container_name: backend
    ports:
      - "5001:80" # Exposing port 80 of the backend container to port 5001 of the host
    networks:
      - iot-network

  monitoring-station-api:
    image: atifhussain28/monitoring-station-api:latest
    container_name: monitoring-station-api
    ports:
      - "5002:80" # Exposing port 80 of the monitoring-station-api container to port 5002 of the host
    networks:
      - iot-network

  sensors:
    image: atifhussain28/sensors:latest
    container_name: sensors
    ports:
      - "5003:80" # Exposing port 80 of the sensors container to port 5003 of the host
    networks:
      - iot-network

  sensors-api:
    image: atifhussain28/sensors-api:latest
    container_name: sensors-api
    ports:
      - "5004:80" # Exposing port 80 of the sensors-api container to port 5004 of the host
    networks:
      - iot-network
    depends_on:
      - monitoring-station-api

  react-frontend:
    image: atifhussain28/frontend:latest
    container_name: react-frontend
    ports:
      - "3000:80" # Exposing port 80 of the react-frontend container to port 3000 of the host
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge
